Transform: AWS::Serverless-2016-10-31
Description: This is a test stack
Parameters:
  TopicName:
    Type: String
  TableName:
    Type: String
  StageName:
    Type: String
  Email:
    Type: String

Globals:
  Api: 
    OpenApiVersion: '3.0.0'
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    MemorySize: 1024
    Environment:
      Variables:
        Webhook_Table: !Sub ${TableName}

Resources:
  myApis:
    Type: AWS::Serverless::Api
    Properties:
      Name: webhook-api
      Description: My webhook api
      StageName: !Sub ${StageName}
      DefinitionUri: output/swagger.yaml
  WebhookTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${TableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  WebhookTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${TopicName}
      Subscription:
        - Endpoint: !Ref Email
          Protocol: email
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/
      Handler: index.handler
      FunctionName: webhook-handler
      Description: Handle webhook from mailgun
      Environment:
        Variables:
          TopicArn: 
            Ref: WebhookTopic
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource:
                - !GetAtt WebhookTable.Arn
            - Effect: Allow
              Action: 
                - "sns:Publish"
                - "SNS:SetTopicAttributes"
              Resource:
                - Ref: WebhookTopic
      Events:
        handleEvents:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
            RestApiId:
              Ref: myApis

